name: turbopy-block-on-spring-app
channels:
        - defaults
dependencies:
        - python=3.7
        - numpy
        - scipy
        - xarray
        - pytest-runner
        - pytest
        - pytest-cov
        - sphinx
        - pip
        - pip:
                - turbopy
